package com.sgat_system.view;

import com.sgat_system.controller.ClassroomController;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joaoc
 */
public class RegistrationClass extends javax.swing.JFrame {

    ClassroomController classroom = new ClassroomController();
    
    /**
     * Creates new form RegistrationClass
     */
    public RegistrationClass() {
        initComponents();
        
        txt_id_class.setText(String.valueOf(classroom.getLastID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_save_registerStu1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_id_registerStu1 = new javax.swing.JLabel();
        txt_id_class = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JcomboBox_studentName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JcomboBox_instructorName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JcomboBox_category = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_day_class = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        JcomboBox_time = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("/ Dashboard / Class Registration");

        btn_back1.setText("< Back");
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Student registration"));

        btn_save_registerStu1.setBackground(new java.awt.Color(0, 255, 102));
        btn_save_registerStu1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_save_registerStu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_registerStu1.setText("Save");
        btn_save_registerStu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_registerStu1ActionPerformed(evt);
            }
        });

        jLabel18.setText("ID Class:");

        jLabel11.setText("Student info:");

        JcomboBox_studentName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JcomboBox_studentNameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JcomboBox_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboBox_studentNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Instructor info:");

        JcomboBox_instructorName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JcomboBox_instructorNameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("Category:");

        JcomboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "A - motorcycle", "B - Car" }));

        jLabel3.setText("Day:");

        try {
            txt_day_class.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Time");

        JcomboBox_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 to 7:50", "8:00 to 8:50", "9:00 to 9:50", "10:00 to 10:50", "11:00 to 11:50", "13:00 to 13:50", "14:00 to 14:50", "15:00 to 15:50", "16:00 to 16:50", "17:00 to 17:50", "18:00 to 18:50" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save_registerStu1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcomboBox_instructorName, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JcomboBox_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_day_class)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_id_class, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_registerStu1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JcomboBox_time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JcomboBox_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_id_registerStu1)
                    .addComponent(txt_id_class))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(JcomboBox_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JcomboBox_instructorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcomboBox_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_day_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcomboBox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save_registerStu1)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        this.dispose();
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void JcomboBox_instructorNameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JcomboBox_instructorNameAncestorAdded

        Vector vector = new Vector();
        ClassroomController classrom = new ClassroomController();

        vector = classrom.comboBoxListInstructorInfo();

        if (vector.size() != 0)
        {
            for (int c = 0; c < vector.size(); c++)
            {
                JcomboBox_instructorName.addItem(String.valueOf(vector.get(c)));
            }
        }
        else
        {
            JcomboBox_instructorName.addItem("No instructors registered");
        }
    }//GEN-LAST:event_JcomboBox_instructorNameAncestorAdded

    private void JcomboBox_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboBox_studentNameActionPerformed

    }//GEN-LAST:event_JcomboBox_studentNameActionPerformed

    private void JcomboBox_studentNameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JcomboBox_studentNameAncestorAdded

        Vector vector = new Vector();
        ClassroomController classrom = new ClassroomController();

        vector = classrom.comboBoxListStudentInfo();

        if (vector.size() != 0)
        {
            for (int c = 0; c < vector.size(); c++)
            {
                JcomboBox_studentName.addItem(String.valueOf(vector.get(c)));
            }
        }
        else
        {
            JcomboBox_studentName.addItem("No student registered");
        }
    }//GEN-LAST:event_JcomboBox_studentNameAncestorAdded

    private void btn_save_registerStu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_registerStu1ActionPerformed

        int id = Integer.parseInt(txt_id_class.getText());
        String nameStudent = String.valueOf(JcomboBox_studentName.getSelectedItem());
        String instructor = String.valueOf(JcomboBox_instructorName.getSelectedItem());
        String categoty = String.valueOf(JcomboBox_category.getSelectedItem());
        String dayClass = txt_day_class.getText();
        String timeClass = String.valueOf(JcomboBox_time.getSelectedItem());
                
        ClassroomController classroom = new ClassroomController();
        
        if (classroom.registerClassroom(id, nameStudent, instructor, categoty, dayClass, timeClass))
        {
            JOptionPane.showMessageDialog(null, "Saved information!", "Successfully", 1);
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Error saving information!", "Error", 0);
        }
        
        this.dispose();
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_btn_save_registerStu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcomboBox_category;
    private javax.swing.JComboBox<String> JcomboBox_instructorName;
    private javax.swing.JComboBox<String> JcomboBox_studentName;
    private javax.swing.JComboBox<String> JcomboBox_time;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_save_registerStu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txt_day_class;
    private javax.swing.JLabel txt_id_class;
    private javax.swing.JLabel txt_id_registerStu1;
    // End of variables declaration//GEN-END:variables
}
